### ISSUE TITLE
no camera found?

### ISSUE THREAD

**Issue by stephanschulz** [yonatanrozin/Facial-Classifier#1]
I tired to set the camera ID to 0 and 1 since I have 2 USB cameras on my macOS M1 computer. But both times no new window opens. But the message `retrieving new frame.` appears many times.

`camID = 1`
![Screen Shot 2023-10-06 at 9 07 15 AM](https://github.com/yonatanrozin/Facial-Classifier/assets/1054816/dc0eb258-5dfe-4b6c-88a5-26f6ef54fc0b)

`camID = 0`
![Screen Shot 2023-10-06 at 9 06 29 AM](https://github.com/yonatanrozin/Facial-Classifier/assets/1054816/3aa49748-af25-4e01-8ccf-3cb591bb098d)

I am not good in python but tried to list all available cameras this way

```
def list_cameras(max_cameras=10):
    available_cameras = []

    for i in range(max_cameras):
        cam = cv2.VideoCapture(i, cv2.CAP_DSHOW)
        if cam is None or not cam.isOpened():
            break
        available_cameras.append(i)
        cam.release()

    return available_cameras
 ```

![Screen Shot 2023-10-06 at 9 10 35 AM](https://github.com/yonatanrozin/Facial-Classifier/assets/1054816/2e026029-8cce-41fe-b3b8-abc35977333f)

**Comment by yonatanrozin** [comment]
Apologies for the difficulty! The specific code for opening the camera
won’t work for every device.

According to the output of your function, try setting the camera id to 1
instead of 0:

cam = cv2.VideoCapture(1, cv2.CAP_DSHOW)

If the issue persists, try the same code, but removing the cv2.CAP_DSHOW.
That argument specifies the api used to interface with the camera. If that
doesn’t work, cv2.CAP_ANY may help.

Let me know if there’s any success!

**Comment by stephanschulz** [comment]
thanks for the tip.

`cam = cv2.VideoCapture(0)` indeed gave me successful access to my usb webcam.
